#!/bin/bash

# Waybar colors are generated by Matugen through Waypaper's post_command.
# This script only reloads Waybar without switching to legacy hardcoded presets.
killall waybar 2>/dev/null
waybar & disown
