source = ~/.config/hypr/matugen-hyprlock.conf

$font_family = FiraCode Nerd Font
$wallpaper = $HOME/.config/dotfiles/lockscreen/wallpaper.jpg
$profile = $HOME/.config/dotfiles/lockscreen/profile.png
$inner_color  = $matugen_lock_inner
$border_color = $matugen_lock_border
$gradient = $matugen_lock_gradient

general {
    grace = 0
}

# Background
background {
    monitor =
    # path = $wallpaper
    path = screenshot
    brightness = 0.5
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
}

# Profile Picture
image {
    monitor =
    path = $profile
    size = 110
    rounding = 10
    border_size = 4
    border_color = $border_color

    position = 20, -20
    halign = left
    valign = top
    zindex = 1
}

# User Info
label {
    monitor =
    text = cmd[update:1000000] echo "$USER\n󰁥 $(hostname)\n\n$(uname -r)"
    shadow_boost = 0.5
    shadow_passes = 1
    color = $matugen_lock_text
    font_size = 11
    font_family = $font_family

    position = 170, -35
    halign = left
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B %Y')" </b>"
    color = $matugen_lock_secondary
    font_size = 14
    font_family = $font_family
    position = 0, 250
    halign = center
    valign = center
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    color = $matugen_lock_tertiary
    shadow_size = 3
    shadow_color = $matugen_lock_shadow
    shadow_boost = 1.2
    font_size = 200
    font_family = $font_family
    position = 0, 100
    halign = center
    valign = center
    zindex = 5
}

# TIME MIN
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = $matugen_lock_primary
    font_size = 200
    font_family = $font_family
    position = 0, -120
    halign = center
    valign = center
    zindex = 5
}

# TIME SEC
label {
    monitor =
    text = cmd[update:1000] date +"%S"
    color = $matugen_lock_secondary
    shadow_size = 3
    shadow_color = $matugen_lock_shadow
    shadow_boost = 1.2
    font_size = 24
    font_family = $font_family
    position = 170, -190
    halign = center
    valign = center
    zindex = 5
}

# Input Field
input-field {
    monitor =
    size = 200, 50

    outline_thickness = 1
    outer_color = $gradient
    inner_color = $inner_color
    font_color = $matugen_lock_text
    check_color = $matugen_lock_check
    fail_color = $matugen_lock_fail # if authentication failed, changes outer_color and fail message color
    capslock_color = $matugen_lock_error # when capslock is active

    fade_on_empty = false
    placeholder_text = 🔒 Password # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = 10 # -1 means complete rounding (circle/oval)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty

    position = 0, -300
    halign = center
    valign = center
    zindex = 10
}

# Failed attempts
label {
    monitor =
    text = Failed Attempts: $ATTEMPTS
    shadow_passes = 1
    shadow_boost = 0.5
    color = $matugen_lock_error
    font_size = 11
    font_family = $font_family

    position = 0, 170
    halign = center
    valign = bottom
}

# Reboot
label {
    monitor =
    text = 󰜉
    color = $matugen_lock_secondary
    font_size = 30
    onclick = reboot now
    position = 0, 50
    halign = center
    valign = bottom
}

# Power off
label {
    monitor =
    text = 󰐥
    color = $matugen_lock_secondary
    font_size = 30
    onclick = shutdown now
    position = 100, 50
    halign = center
    valign = bottom
}

# Suspend
label {
    monitor =
    text = 󰤄
    color = $matugen_lock_secondary
    font_size = 30
    onclick = systemctl suspend
    position = -100, 50
    halign = center
    valign = bottom
}
