# Enable true colors
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Enable mouse mode
set -g mouse on

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

bind-key j command-prompt -p "join pane from window:" "join-pane -h -s :%% -l 35%"
bind-key b break-pane
