exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = dotfiles-wallpaper_engine --random
exec-once = ~/.config/hypr/scripts/gamemode.sh cleanup

exec-once = swaync
exec-once = waybar
exec-once = hypridle

exec-once = wl-paste --watch cliphist store

exec-once = solaar -w hide

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
