# -----------------------------------------------------
# HyprExpo
# -----------------------------------------------------

exec = ~/.config/hypr/scripts/load-hyprexpo.sh

plugin {
  hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = rgb(111111)
    workspace_method = center current
    skip_empty = false
    gesture_distance = 300
  }
}
