[portals]
default=hyprland;wlr
org.freedesktop.impl.portal.ScreenCast=hyprland;wlr
org.freedesktop.impl.portal.Screenshot=hyprland;wlr
org.freedesktop.impl.portal.Inhibit=hyprland;wlr
org.freedesktop.impl.portal.Settings=hyprland
org.freedesktop.impl.portal.FileChooser=hyprland
org.freedesktop.impl.portal.AppChooser=hyprland
